-- MySQL Script generated by MySQL Workbench
-- Thu May 26 22:00:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja` DEFAULT CHARACTER SET utf8 ;
USE `loja` ;

-- -----------------------------------------------------
-- Table `loja`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`client` (
  `id_client` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` CHAR(11) NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `active` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `loja`.`object`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`object` (
  `id_object` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preco` VARCHAR(45) NOT NULL,
  `image` INT(11) NOT NULL,
  `descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_object`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `loja`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(30) NOT NULL,
  `password` VARCHAR(72) NOT NULL,
  `is_temp_password` TINYINT NOT NULL,
  `id_client` INT UNSIGNED NOT NULL,
  `client_id_client` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_user`, `id_client`, `client_id_client`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) ,
  INDEX `fk_user_client_idx` (`client_id_client` ASC) ,
  CONSTRAINT `fk_user_client`
    FOREIGN KEY (`client_id_client`)
    REFERENCES `loja`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
